### ISSUE TITLE
Nothing happens with "./cassiectrl"?

### ISSUE THREAD

**Issue by littleggghost** [agilityrobotics/cassie-gazebo-sim#2]
After I running the gazebo and loading cassie successfully, I run the "./cassiectrl" in another terminal and nothing happens with the only output "Connecting to cassie...".
What it should happen? How to fix it?

**Comment by whtqh** [comment]
Sure, when `gazebo cassie.world` runs.
A Null Controller of ./cassiectrl will connect to the gazebo and really do "something?" in the gazebo world.
But, we can see "Null"-thing happens. ~~~lol~~~

**Comment by sahilkejriwalagility** [comment]
@littleggghost After running `./cassiectrl` there should be a "Connected!" message displayed on the terminal. It does not command any torques to the robot. 
I second @whtqh on setting the environment variable.

**Comment by littleggghost** [comment]
Thanks for your replies!
