### ISSUE TITLE
About function cassie_core_sim_step

### ISSUE THREAD

**Issue by Arthur-sky** [agilityrobotics/cassie-gazebo-sim#6]
- I try to control torque of joints by sending 
```C++
typedef struct {
  double torque[10];
  short telemetry[9];
} cassie_user_in_t;
```
- I gauss torque is the command torque to joints
- However, in the plugin, user input is processed by function  cassie_core_sim_step, and something strange come out, may i ask why? 
- Besides, how to use the parameter [telemetry]?
@sahilkejriwalagility

**Comment by sahilkejriwalagility** [comment]
Hi @Arthur-sky,

The `cassie_user_in_t` is struct generated by the user controller. The function `cassie_core_sim_step` converts the user input `cassie_user_in_t` and passes it through a function which converts it to cassie specific inputs(after doing various safety checks, etc.) `cassie_in_t`. `cassie_in_t` is fed to the robot and what comes out of the robot is `cassie_out_t`.

The parameter `telemetry` is used internally to display data on the radio controller from `cassie_out_t`. It is elements 6-14 in https://github.com/agilityrobotics/cassie-gazebo-sim/blob/master/plugin/include/cassie_out_t.h#L68.
