### ISSUE TITLE
De_cassie.h: No such file or directory

### ISSUE THREAD

**Issue by kangbojk** [agilityrobotics/cassie-gazebo-sim#7]
Hi @sahilkejriwalagility ,

I tried to build the example in plugin folder, but couldn't find files like "De_cassie.h" "Ce_cassie.h" "Ge_cassie.h".
Could you provide these files to help it build?

BTW, I would like to know how you setup inertia properties of cassie meshes. I tried to export my own meshed from solidworks, but the inertia values weren't that correct, the inertia box seemed too big to cover the meshes.

Thanks.

**Comment by sahilkejriwalagility** [comment]
Hi @kangbojk, 

I was not able to replicate this error. It would be helpful if you can send me the logs.

We directly imported the inertias from the CAD software and it worked just fine.

-Sahil

**Comment by uniqueluo** [comment]
Hi @sahilkejriwalagility ,

Which version of CAD do you use?,and how to export inertias properties.

**Comment by sahilkejriwalagility** [comment]
> Hi @sahilkejriwalagility ,
> 
> Which version of CAD do you use?,and how to export inertias properties.

Like I said, Inertia properties can be directly exported from the CAD software you are using. The inertia properties for cassie are included in the sdf file.
